### ISSUE TITLE
Tekstiominaisuuksien lokasointimahdollisuus jätetty toteuttamatta

### ISSUE THREAD

**Issue by ilkkarinne** [YM-rakennettu-ymparisto/kaavatietomalli-kuntapilotti#17]
Seuraavat ominaisuudet on UML.mallissa tarkoitettu lokalisoitaviksi, eli ne tulee voida antaa useammalla kuin yhdellä kielellä:
* InformativeFeature / name
* SpatialPlan / name
* ZoningElement / name
* NumericalValue / description
* RegulativeText / description
* OrdinanceProcessEvent / name

GML-skeemassa kaikki nämä on toteutettu xs:string -tyypin ominaisuuksina ilman mahdollisuutta antaa tekstin kielikoodi.

GML Simple Features Profile:ssa lokalisoidun merkkijonon kuvaaminen käsitellään luvussa "8.4.4.7.2 Internationalized string": lokalisoitu merkkijonotyyppi tulee määritellä skeemaan, ja sen sisällön kieli määritellään ```xml:lang```-attribuutin avulla.

UML-mallin viimeisimmän version SpatialPlan-luokkaan on myös lisätty pakollinen language-ominaisuus, joka rajoittaa kaavan vain yhdelle kielelle. Tämä on ristiriitaista UML-mallissa muualla esiintyvän monikielisuuden tuen kanssa, ja tekee kaavatietomallin mukaisen kaavatiedon julkaisemisen monikielisenä käytännössä mahdottomaksi: Samasta kaavasta ei voi olla monia kieliversioita eri SpatialPlan-kohteina, koska kyse on samasta paikkatietokohteesta.

**Comment by marira** [comment]
Järkevä muutos, keskustellaan vielä language-parametrin poistamisesta. Lisätään luetelluille ominaisuuksille kielimääritys seuraavassa skeemaversiossa.

**Comment by ilkkarinne** [comment]
Muutetaan muutosehdotusta, ks. https://github.com/YM-rakennettu-ymparisto/kaavatietomalli/issues/22#issuecomment-440998497

**Comment by ilkkarinne** [comment]
Korjattu OK
