### ISSUE TITLE
ZoningElementin ReferencedFeature-viittaus epäkonsistentti UML-mallin kanssa

### ISSUE THREAD

**Issue by ilkkarinne** [YM-rakennettu-ymparisto/kaavatietomalli-kuntapilotti#18]
UML-mallissa ei ole yhteyttä ZoningElement- ja ReferencedFeature-luokkien välillä, ainoastaan SpatialPlan voi sisältää 0..n viittausta ReferencedFeature-tietotyyppiin. GML-skeemassa ZoningElement-tyypillä on ominaisuus affectingFeature- joka viittaa ReferencedFeatureen. Joko UML-mallia tai GML-skeemaa tulee korjata, jotta tietomalli on toteutettu konsistentisti.

**Comment by marira** [comment]
Hyvä huomio. Lisätään viittaus UML-kaavioon. Mitä tarkemmalle tasolle kohteet saadaan linkattua, sitä parempi.

**Comment by ilkkarinne** [comment]
Muuttaisin yhteyden siten, että ei olisi aggregaatio, vaan suunnattu viittaus (ZoningElement->ReferencedFeature) kuten SpatialPlan -> ReferencedFeature. Muuten OK.

**Comment by AlbMak** [comment]
SpatialPlan-tyypin affectingIncludedFeature viittaa <feature>-kohteeseen InformativeFeature. Tämä elementti kannattaisi varmaan muuttaa gml:ReferenceTypeksi ja asettaa viittamaan feature-kokoelmassa olevaan InformativeFeatureen?

**Comment by ilkkarinne** [comment]
> SpatialPlan-tyypin affectingIncludedFeature viittaa -kohteeseen InformativeFeature. Tämä elementti kannattaisi varmaan muuttaa gml:ReferenceTypeksi ja asettaa viittamaan feature-kokoelmassa olevaan InformativeFeatureen?

Kyllä, hyvä huomio

**Comment by ilkkarinne** [comment]
Korjattu OK
