### ISSUE TITLE
Uudelleenmääritellyt GML-ominaisuudet

### ISSUE THREAD

**Issue by ilkkarinne** [YM-rakennettu-ymparisto/kaavatietomalli-kuntapilotti#22]
Seuraavat UML-kaavion ominaisuudet on merkitty uudelleenmääritellyiksi samannimisestä peritystä GML-luokan ominaisuudesta:
* AbstractReferencedResource/identifier (0..1 > 1..1)
* AbstractPlannngObject/identifier (0..1 > 1..1)
* InformativeFeature/name (GenericName -> LocalizedGenericName)
*  SpatialPlan/name (0..n, GenericName ->1..n, LocalizedGenericName)
* ZoningElement/name (0..n, GenericName -> 1..n, LocalizedGenericName, kaaviosta puuttuu tieto uudelleenmääritteystä, ja moninaisuus on 1..1, mutta tämä lienee vahinko)
* NumericValue/description (0..1, CharacterString -> 0..n, LocalizedCharacterString)
* RegulativeText/description (0..1, CharacterString -> 0..n, LocalizedCharacterString)
* OrdinanceProcessEvent/name (0..n, GenericName -> 1..n, LocalizedGenericName)

Perittävän GML-.tyypin ominaisuuksien muuttaminen tehdään XML-skeemassa restiction-määrittelyllä. Koska yksi GML-tyyppi ei voi samaan aikaan sekä rajoittaa että laajentaa perittävää luokkaa, tulee yllä olevan kaltaiset ominaisuudet toteuttaa laatimalla ensin tarpeellisin osin rajoitetut tyypit perittävistä abstrakteista GML-tyypeistä (gml:AbstractGMLType and gml:AbstractFeatureType tässä tapauksessa), ja laajentaa näitä rajoitettuja tyyppejä varsinaisissa skeeman tyyppimäärittelyissä.

Mikäli uudelleenmääriteltyjen ominaisuuksien määrittelyssä ei olla tarkkoina, ongelmille dataa käsittelevien sovellusten toteuttamisessa kasvaa. Tyypillisesti sovellukset eivät suhtaudu hyvin esim. tilanteisiin, joissa samassa GML-tyypissä on samannimisiä, mutta eri tavoin määritelyjä attribuutteja (osa perittyjä, osa määritelty suoraan tyypissä).

**Comment by ilkkarinne** [comment]
Tarkemmalla tutkimisella aiempi kommenttini on teknisesti hieman turhan riskialtis ja monimutkainen lokalisoitujen name- ja description-ominaisuuksien osalta, sillä sekä niiden tyyppiä että moninaisuutta pitäisi muuttaa.

Suosittelen siis sen sijaan seuraavaa:

1. Lisätään InformativeFeature, SpatialPlan, ZoningElement, OrdinanceProcessEvent-luokkia vastaaviin GML-tyyppeihin uusi localizedName-ominaisuus, esim.

```xml
<xs:complexType name="LocalizedNameType">
  <xs:simpleContent>
    <xs:extension base="gml:CodeType">
      <xs:attribute ref="xml:lang" use="optional" />
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>
...
<xs:element name="localizedName" type="kt:LocalizedNameType" maxOccurs="unbounded"/>
```
(InformativeFeature:ssa minOccurs="0")

Tällä tavoin alkuperäinenkin name jää olemaan tuon localizedName:n kanssa, mutta vältetään samasta nimestä johtuva konflikti.

Vastavasti NumericValue- ja RegulativeText-luokkia vastaaviin GML-tyyppeihin lisätään uusi localizedDescription-ominaisuus:

```xml
<xs:complexType name="LocalizedDescriptionType">
  <xs:simpleContent>
    <xs:extension base="gml:StringOrRefType">
      <xs:attribute ref="xml:lang" use="optional" />
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>
...
<xs:element name="localizedDescription" type="kt:LocalizedDescriptionType" minOccurs="0" maxOccurs="unbounded"/>
```

2. Rajoitetaan AbstractGMLType- ja AbstractFeatureType-tyyppejä tekemällä gml:identifier-ominaisuus pakolliseksi:

```xml
<xs:complexType name="AbstractGMLWithMandatoryIdentifierType">
  <xs:complexContent>
    <xs:restriction base="gml:AbstractGMLType">
      <xs:sequence>
        <xs:element ref="gml:metaDataProperty" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="gml:description" minOccurs="0"/>
          <xs:element ref="gml:descriptionReference" minOccurs="0"/>
          <xs:element ref="gml:identifier" minOccurs="1"/>
          <xs:element ref="gml:name" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="gml:id"/>
      </xs:restriction>
   </xs:complexContent>
</xs:complexType>
	
<xs:complexType name="AbstractFeatureWithMandatoryIdentifierType">
  <xs:complexContent>
    <xs:restriction base="gml:AbstractFeatureType">
      <xs:sequence>
        <xs:element ref="gml:metaDataProperty" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="gml:description" minOccurs="0"/>
        <xs:element ref="gml:descriptionReference" minOccurs="0"/>
        <xs:element ref="gml:identifier" minOccurs="1"/>
        <xs:element ref="gml:name" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="gml:boundedBy" minOccurs="0"/>
        <xs:element ref="gml:location" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute ref="gml:id"/>
    </xs:restriction>
  </xs:complexContent>
</xs:complexType>
```
Muutetaan sitten AbstractReferenceResource laajentamaan rajoitettua AbstactGMLType-tyyppiä:
```xml
<xs:element name="AbstractReferencedResource" type="kt:AbstractReferencedResourceType" abstract="true" substitutionGroup="gml:AbstractGML"/>
<xs:complexType name="AbstractReferencedResourceType" abstract="true">
  <xs:complexContent>
    <xs:extension base="kt:AbstractGMLWithMandatoryIdentifierType">
    ...
```

ja AbstractPlanningObject laajentamaan rajoitettua AbstractFeatureType-tyyppiä:
```xml
<xs:element name="AbstractPlanningObject" type="kt:AbstractPlanningObjectType" abstract="true" substitutionGroup="gml:AbstractFeature"/>
<xs:complexType name="AbstractPlanningObjectType" abstract="true">
  <xs:complexContent>
    <xs:extension base="kt:AbstractFeatureWithMandatoryIdentifierType">
...
```

Huomaa, että korvausryhmän (substitutionGroup) nimi ei muutu, ja elementtityyppejä AbstractGMLWithMandatoryIdentifier ja AbstractFeatureWithMandatoryIdentifier ei tarvitse määritellä.

**Comment by AlbMak** [comment]
Miksi kohdassa 1. laajennat tyypin LocalizedNameType tyypistä gml:CodeType, mutta tyypin LocalizedDescriptionType laajennat tyypistä gml:StringOrRefType?

StringOrRefType:n kohdalla gml-skeeman annotaatiossa lukee "deprecated".

Skeemassa on määritetty jo kielityyppi:
<xs:complexType name="LanguageStringType">
  <<xs:simpleContent>>
      <xs:extension base="xs:string">
         <xs:attribute ref="xml:lang" use="optional" />
     </xs:extension>
  </xs:simpleContent>
</xs:complexType>

Tätä tyyppiä käytetään lokalisoiduissa elementeissä. Mikä vika on tuossa tyypissä?

**Comment by ilkkarinne** [comment]
Valitsin nuo laajennettavat tyypit sen perusteella, että gml:name ja gml:description laajentavat ko. tyyppejä. Näin voi olla varma, että täysin samoja sisältöjä, joita käytetään GML:n name- ja description-elementeissä (aatirbuutteineen) voidaan käyttää myös localizedName ja localizedDescription-elementeissä. Ei sillä tässä tapauksessa suurta merkitystä tässä taida olla käyttääkö suoraan xs:string:stä laajentavaa tyyppiä.

Määrittelisin nimell ja kuvaustekstille kuitenkin jo valmiksi eri tyypit, koska on nähtävissä, että näiden merkkijonojen pituutta voidaan haluta rajoittaa (esim. tietokantatallennussyistä), ja tuolloin nimelle todennäköisesti varataan vähemmän tilaa kuin kuvaustekstille. Kun ne ovat valmiiksi eri tyyyppejä, niin niiden rajoittaminen erimittaisiksi voidaan tehdä hyvin kevyellä skeemamuutoksella myöhemmin.

**Comment by ilkkarinne** [comment]
Korjattu OK
