### ISSUE TITLE
Arvo VP (Puisto) puuttuu koodilista-toteutuksesta FinnishLandUseKind

### ISSUE THREAD

**Issue by ilkkarinne** [YM-rakennettu-ymparisto/kaavatietomalli-kuntapilotti#23]
https://github.com/YM-rakennettu-ymparisto/kaavatietomalli/blob/e299d1715ee26c5270f9e21112e34f4887b3641d/xmlschema/kaavoituksenKansallinenTietomalli_Tyypit.xsd#L131-L524

Kannattanee tarkistaa muutkin listat ja arvot (jos ei jo suoraan siirrytä gml:ReferenceType:n käyttöön, ks. #21)

**Comment by marira** [comment]
Nyt on siirrytty gml:ReferenceType:n käyttöön
