### ISSUE TITLE
Kaavaselostus / PlanDescriptionType

### ISSUE THREAD

**Issue by solismaam** [YM-rakennettu-ymparisto/kaavatietomalli-kuntapilotti#25]
Skeemassa on kaksi complextypeä nimellä PlanDescriptionType - [rivillä 449](https://github.com/YM-rakennettu-ymparisto/kaavatietomalli/blob/master/xmlschema/kaavoituksenKansallinenTietomalli.xsd#L449) ja [rivillä 463](https://github.com/YM-rakennettu-ymparisto/kaavatietomalli/blob/master/xmlschema/kaavoituksenKansallinenTietomalli.xsd#L463) - tulisiko jälkimmäisen olla nimeltä  PlanDescriptionPropertyType?

**Comment by marira** [comment]
Kyllä, tuossa oli virhe ja se on nyt korjattu
