### ISSUE TITLE
plannedSpace-elementti pienellä

### ISSUE THREAD

**Issue by ilkkarinne** [YM-rakennettu-ymparisto/kaavatietomalli-kuntapilotti#27]
plannedSpace-elementti ja plannedSpaceType-tyyppi on kirjoitettu pienellä alkukirjaimella.

https://github.com/YM-rakennettu-ymparisto/kaavatietomalli/blob/6e6ab7b001c4ffb5434e111ba784ad36cb1aaa54/xmlschema/kaavoituksenKansallinenTietomalli.xsd#L274-L275

**Comment by marira** [comment]
Selkeä virhe, korjataan

**Comment by ilkkarinne** [comment]
Korjattu OK, commit 885022eca0dc6bebee8e47893864c17edfe7e192
